---
- name: Configurar servicio web en el router CSR1kv en puerto 9999
  hosts: routers
  gather_facts: false

  tasks:
    - name: Habilitar servidor HTTP y cambiar el puerto a 9999 en el CSR1kv
      ios_config:
        lines:
          - ip http server
          - ip http secure-server
          - ip http port 9999
          - ip http secure-port 9999