---
- name: AUTOMATIC BACKUP OF RUNNING-CONFIG
  hosts: routers
  gather_facts: false

  tasks:
    - name: Asegurar que el directorio de respaldos exista localmente
      ansible.builtin.file:
        path: "./backups"
        state: directory
        mode: '0755'

    - name: Obtener el running-config del CSR1kv
      ios_command:
        commands:
          - show running-config
      register: config

    - name: Guardar la salida en la carpeta local ./backups/
      ansible.builtin.copy:
        content: "{{ config.stdout[0] }}"
        dest: "./backups/show_run_{{ inventory_hostname }}.txt"